language: ruby
rvm:
  - 2.2
before_script:
  - wget https://codeload.github.com/dkhamsing/awesome_bot/tar.gz/wip -O /tmp/temp.tar.gz
  - tar -xvf /tmp/temp.tar.gz
  - export PATH=$PATH:$PWD/awesome_bot-wip/bin/
  - cd awesome_bot-wip
  - bundle install
script:  
  - awesome_bot ../README.md
